== Robots

=== Control

. Robots must be controlled autonomously. The use of a remote control, manual control, or passing information (by external sensors, cables, wirelessly, etc.) to the robot is not allowed.

. Robots must be started manually by the team captain.

. Robots may utilize various maze navigation algorithms. Any pre-mapped type of dead reckoning (movements predefined based on known locations or placement of features in the field) is prohibited.

. A robot must not damage any part of the field in any way.

=== Construction

. The height of a robot must not exceed 30 cm.

. Robots may not have any sensors or devices that enables it to 'see' over the walls.

. Any robot kit or building blocks, either available on the market or built from raw hardware, may be used as long as the design and construction are primarily and substantially the original work of the students (see section 3.5. below).

. Teams are not permitted to use any commercially produced robot kits or sensors components that are specifically designed or marketed to complete any single major task of RoboCupJunior Rescue. Robots that do not comply will face immediate disqualification from the tournament. If there is any doubt, teams should consult the RoboCupJunior Maze Entry Working Group prior to the competition.

. For the safety of participants and spectators, only lasers of class 1 and 2 are allowed. This will be checked during inspection. Teams using lasers must have the datasheet of the laser, and also must  submit them prior to the competition as well as be able to show them during the competition.

. Wireless communication must be used correctly as described on the https://junior.robocup.org/robocupjunior-general-rules/[RoboCupJunior General Rules]. Robots performing other types of wireless communication need to be deleted or disabled. If the robot  has other forms of wireless communication equipment, the team needs to prove that they are
disabled. Non-conforming robots may be immediately disqualified from the tournament.

. Robots may incur damage by falling off the field, making contact with another robot, or making contact with field elements.  The organizing committee cannot anticipate all potential situations where damage to the robot may occur. Teams should ensure that all active elements on a robot are properly protected with resistant materials. For example, electrical circuits must be protected from all human contact and direct contact with other robots and field elements.

. When batteries are transported, moved or charged, it is strongly recommended that safety bags be used. Reasonable efforts should be made to ensure that robots avoid short circuits and chemical or air leaks.

. Robots must be equipped with a handle which is to be used to pick them up during the scoring run.

. Robots must be equipped with a single binary switch or button(s) or any kind, clearly visible to the referee, specifically for restarting the robot when a lack of progress occurs.

=== Team

. Each team must have only one robot in the field.

. Each team must comply with the https://junior.robocup.org/robocupjunior-general-rules/[RoboCupJunior General Rules] regarding the number of members and each member’s age.

. The Rescue Maze Entry League is open to students in the age from 10 to 16 years (age as of 1st of
July).

. Each team member will need to explain their work and should have a specific technical role.

. A student can be registered on only one team across all RoboCupJunior leagues/sub-leagues.

. A team is only allowed to participate in one league/sub-league in across all RoboCupJunior leagues/sub-leagues.

. A participant may only participate twice in an Entry league competition of a regional RCJ qualification final (e.g. German Open, Portuguese Open, etc.). A participant is allowed to participate in a qualification competition for a regional final without restrictions.

. Mentors/parents are not allowed to be with the students during the competition. The students will have to self-govern themselves (without mentor's supervision or assistance) during the long stretch of hours at the competition.


=== Inspection

. The robots will be scrutinized by a panel of referees before the start of the tournament and at other times during the competition to ensure that they meet the constraints described in these rules.

. It is illegal to use a robot that is very similar to another team’s robot from a previous year or the current year.

. It is the responsibility of the team to have their robot re-inspected, if their robot is modified at any time during the tournament.

. Students will be asked to explain the operation of their robot in order to verify that construction and programming of the robot is their own work.

. Students will be asked about their preparation efforts and may be requested to answer surveys and participate in video-taped interviews for research purposes.

. All teams must complete a web form prior to the competition to allow referees to better prepare for the interviews. Instructions on how to submit the form will be provided to the teams prior to the competition.

. All teams have to submit their source code prior to the competition. The source code will not be shared with other teams without the team’s permission.

. All teams must submit their engineering journal prior to the competition. The journals will not be shared with other teams without the team’s permission.

NOTE:  However, it is highly recommended that teams publicly share their engineering journal. With the teams that indicate that their engineering journals could be shared publicly during the registration process, the journal alongside their poster presentation will be shared through the RoboCupJunior Forum so that other teams could learn from them.


=== Violations

. Any violations of the inspection rules will prevent the offending robot from competing until modifications are made and the robot passes inspection.

. Modifications must be made within the time schedule of the tournament and teams cannot delay tournament play while making modifications.

. If a robot fails to meet all specifications (even with modifications), it will be disqualified from that round (but not from the tournament).

. No mentor assistance is allowed during the competition. (See <<Code of Conduct>>)

. Any violations of the rules may be penalized by disqualification from the tournament or the round or may result in a loss of points at the discretion of the referees, officials, organizing committee or general chairs.
